vim.keymap.set('n', '<c-t>', ':ToggleTerm direction=vertical size=60 dir=$pwd<CR>')
vim.keymap.set('n', '<c-b>', ':NvimTreeClose<CR>')
vim.keymap.set('n', '<c-n>', ':NvimTreeOpen<CR>')
vim.keymap.set('n', '<c-q>', ':bd<CR>')
vim.keymap.set('n', '<c-a>', ':bd!<CR>')
